import type { Metadata } from "next";
import "../mdx.css";
import Sidebar from "@/components/sidebar";
import Navbar from "@/components/navbar";
import Footer from "@/components/footer";

export const metadata: Metadata = {
  title: {
    default: "Components",
    template: "%s | Webdrei UI",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const components = Array.from(Array(100).keys());

  // use scrool component from shdcn
  return (
    <>
      <Navbar />

      <div className="flex container pt-[70px]">
        <Sidebar />
        <main className="py-4 w-full pl-8">{children}</main>
      </div>
      <Footer />
    </>
  );
}
