import type { Metadata } from "next";
import Link from "next/link";
import "../mdx.css";
import { ArrowRightIcon } from "@radix-ui/react-icons";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const components = Array.from(Array(100).keys());

  // use scrool component from shdcn
  return (
    <div className="flex">
      <aside className="w-[300px] py-4 h-[100vh] sticky top-[70px]">
        <h2 className="font-bold mb-4">Components</h2>
        <ul className="">
          <li>
            <Link href="/components/button">Button</Link>
          </li>
          <li>
            <Link href="/components/card">Card</Link>
          </li>
          <li className="flex items-center gap-2">
            <Link href="/components/background-absorbers">
              Background Absorbers
            </Link>
          </li>

          <li>
            <Link href="/components/background-among-us">
              Background Among Us
            </Link>
          </li>
          <li>
            <Link href="/components/background-rainbow-fountains">
              Background Rainbow Fountains
            </Link>
          </li>

          <li>
            <Link href="/components/background-links">Background Links</Link>
          </li>

          <li>
            <Link href="/components/background-fire">Background Fire</Link>
          </li>
          <li>
            <Link href="/components/background-big-circles">
              Background Big Circles
            </Link>
          </li>

          <li>
            <Link href="/components/background-stars">Background Stars</Link>
          </li>
        </ul>
      </aside>
      <main className="py-4 w-full">{children}</main>
    </div>
  );
}
