import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Button",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return children;
}
